# Generated by Django 4.1.2 on 2023-07-16 14:15

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_news_remove_image_description_remove_image_horiimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='squareImg',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='squareDefault.png', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='square'),
        ),
        migrations.AlterField(
            model_name='news',
            name='squareImg',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='squareDefault.png', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='square'),
        ),
        migrations.AlterField(
            model_name='puppies',
            name='squareImg',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='squareDefault.png', force_format=None, keep_meta=True, quality=75, scale=None, size=[1000, 1000], upload_to='square'),
        ),
    ]
