# Generated by Django 4.1.2 on 2023-07-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_image_squareimg_alter_news_squareimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_display',
            field=models.DateField(blank=True, null=True),
        ),
    ]
