# Generated by Django 4.1.2 on 2023-07-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_news_date_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='date_display',
            field=models.DateField(null=True),
        ),
    ]
