# Generated by Django 4.1.2 on 2023-07-17 08:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_news_date_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='squareImg',
        ),
        migrations.AddField(
            model_name='news',
            name='horiImg',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='defaultH.jpg', force_format=None, keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='horizontal'),
        ),
    ]
